### ISSUE TITLE
Option to only apply for public methods

### ISSUE THREAD

**Issue by angularsen** [aelij/ConfigureAwaitChecker#2]
The idea is sound, but I honestly don't want to add ConfigureAwait to _every_ await statement. For non-GUI libraries, I find it reasonable to only add this to the public methods and I'd like this plugin to help me not forget them. Thoughts?

**Comment by aelij** [comment]
I think it's too risky. Non-public methods could easily be called from a thread that has a synchronization context, and this could become a big performance issue and even cause deadlocks. There's even a pattern for creating `async` methods for public APIs that says the `async` method should be private, so that the public method could do argument validation before starting the asynchronous operation.

If you look at the Roslyn repository (https://github.com/dotnet/roslyn/) you'll see they've used `ConfigureAwait` with _every_ await. They even use an analyzer that is similar to this project.

**Comment by angularsen** [comment]
Good points, but I think in the end it comes down to preference.
What about making it an option that is disabled by default? 

I don't know how the plugin settings work, but hopefully it follows R#'s setting system where you can save per-solution and per-machine etc.

**Comment by aelij** [comment]
I'll consider it. And you can always fork... :)

**Comment by angularsen** [comment]
Absolutely, I'll consider that too.
